# Generated by Django 2.2.7 on 2019-12-25 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='lg_desc',
            field=models.TextField(default='Long Description'),
            preserve_default=False,
        ),
    ]
